### ISSUE TITLE
Support of typescript / expose threejs loaders apis

### ISSUE THREAD

**Issue by Aarbel** [callum-gander/online-3d-viewer-next-js#1]
thanks @callum-gander for this amazing work

- do you plan to provide typescript on this project ?
- do you also plan to expose easily the loaders APIs, like ifc-js loader API that provides cutting tools ?

**Comment by Aarbel** [comment]
My other question is: who did you use the librqry without hqving qny IDE completions importing this lib ?
<img width="450" alt="image" src="https://user-images.githubusercontent.com/25119847/205657995-ec407749-1103-4dba-9e22-fd028db98445.png">

<img width="346" alt="image" src="https://user-images.githubusercontent.com/25119847/205657929-ed511257-f24b-46a9-b03e-f81377533efd.png">

**Comment by callum-gander** [comment]
These are questions for the maintainer of the main repo, which I know you've already asked so they'll be followed up there. I don't plan to add to this unless there are substantial changes to the main package
